spring:
  profiles:
    active: @profiles.active@
dubbo:
  application:
    name: @project.artifactId@
  provider:
    validation: false
    timeout: 3000
  consumer:
    timeout: 3000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.gita.backend.model
server:
  servlet:
    context-path: /user
