dubbo:
  application:
    id: dubbo-consumer
    name: dubbo-consumer-name
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  registry:
    id: dubbo-consumer
    address: zookeeper://zk1.d.xqcx.com:2181?backup=zk2.d.xqcx.com:2181,zk3.d.xqcx.com:2181
# redis setting
redis:
  host: 127.0.0.1
  port: 6379
logging:
  level:
    org.springframework.security: info
  path: /usr/local/project/logs/@project.artifactId@
